services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_hakyoff
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: hakyoff
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    command: [ "mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0" ]

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge
